// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://czshkxhydilxhvptawoc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN6c2hreGh5ZGlseGh2cHRhd29jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE4NDM2OTUsImV4cCI6MjA1NzQxOTY5NX0.n0PcB6yzZj8fCQfHHmK3Ble2vBD4XcYeP7zuaPpglyM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);